name       : okular
version    : 17.08.2
release    : 14
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/okular-17.08.2.tar.xz : c56f57dc47b8c00208e374f3249d2cf69d6293cb9ebfeeb3601f1c64cbc37e56
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : office.viewers
summary    : KDE document viewer
description: |
    Okular is a universal document viewer developed by KDE. Okular combines the excellent functionalities with the versatility of supporting different kind of documents.
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(phonon4qt5)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - chmlib-devel
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdegraphics-mobipocket-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kjs-devel
    - kio-devel
    - kparts-devel
    - kpty-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libjpeg-turbo-devel
    - libkexiv2-devel
    - threadweaver-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/applications/org.kde.mobile.*.desktop
    cd $installdir; qml_cache
