name       : okular
version    : 21.04.2
release    : 70
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/okular-21.04.2.tar.xz : 330dbe847409bfc544093ac703754fb5f43398ea3dbea88b976dc393d3bda65c
homepage   : https://kde.org/applications/office/org.kde.okular
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.viewers
summary    : KDE document viewer
description: |
    Okular is a universal document viewer developed by KDE. Okular combines the excellent functionalities with the versatility of supporting different kind of documents.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(ddjvuapi)
    - pkgconfig(libmarkdown)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(libzip)
    - pkgconfig(phonon4qt5)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - chmlib-devel
    - ebook-tools-devel
    - kactivities-devel
    - karchive-devel
    - kcrash-devel
    - kdegraphics-mobipocket-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kparts-devel
    - kjs-devel
    - kpty-devel
    - kwallet-devel
    - libjpeg-turbo-devel
    - libkexiv2-devel
    - purpose-devel
    - threadweaver-devel
setup      : |
    %patch -p1 -i $pkgfiles/0001-Solus-default-tweaks-to-okular.patch
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DBUILD_OKULARKIRIGAMI=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/applications/org.kde.mobile.*.desktop

    #remove doc
    rm -rf $installdir/usr/share/doc
