name       : okular
version    : 20.04.3
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/okular-20.04.3.tar.xz : 60865a5d09f41d30572b72224fb61baf9dde18cf6e246565d852e672e7bc4cfe
homepage   : https://kde.org/applications/office/org.kde.okular
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : office.viewers
optimize   : lto
summary    : KDE document viewer
description: |
    Okular is a universal document viewer developed by KDE. Okular combines the excellent functionalities with the versatility of supporting different kind of documents.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5TextToSpeech)
    - pkgconfig(ddjvuapi)
    - pkgconfig(libKActivities)
    - pkgconfig(libmarkdown)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(libzip)
    - pkgconfig(phonon4qt5)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - chmlib-devel
    - ebook-tools-devel
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdegraphics-mobipocket-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kjs-devel
    - kpty-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libjpeg-turbo-devel
    - libkexiv2-devel
    - purpose-devel
    - threadweaver-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF \
                -DBUILD_OKULARKIRIGAMI=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm -rf $installdir/usr/share/applications/org.kde.mobile.*.desktop

    #remove doc
    rm -rf $installdir/usr/share/doc
