name       : okular
version    : 16.12.0
release    : 2
source     :
    - http://download.kde.org/stable/applications/16.12.0/src/okular-16.12.0.tar.xz : 6dd55badaa1dbdacd5bc412a2f34c5f027e51873c89166a6f8c6015608120f29
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.0
component  : office.viewers
summary    : KDE document viewer
description: |
    Okular is a universal document viewer developed by KDE. Okular combines the excellent functionalities with the versatility of supporting different kind of documents.
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(phonon4qt5)
    - pkgconfig(poppler)
    - pkgconfig(poppler-qt5)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - chmlib-devel
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdegraphics-mobipocket-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kjs-devel
    - kio-devel
    - kparts-devel
    - kpty-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libjpeg-turbo-devel
    - libkexiv2-devel
    - threadweaver-devel
rundeps    :
    - breeze-icons
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-breeze-icons-by-default.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
